# Generated by Django 4.0 on 2024-05-20 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0002_chapter_comment_manga_user_avatar_user_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manga',
            name='total_chapter',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
