# Generated by Django 4.0 on 2024-05-20 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0003_alter_manga_total_chapter'),
    ]

    operations = [
        migrations.AddField(
            model_name='manga',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
