# Generated by Django 4.0 on 2024-05-26 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0004_manga_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='manga',
            field=models.ForeignKey(default='1b4f4425-7ff0-46b1-be16-fb98c19deb20', on_delete=django.db.models.deletion.CASCADE, to='engine.manga'),
            preserve_default=False,
        ),
    ]
