# Generated by Django 4.0 on 2024-05-26 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0006_remove_history_manga_history_chapter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='chapter',
        ),
    ]
